markdown: kramdown
highlighter: rouge
permalink: none
sitename: Web 开发博客

chapters:
- introduction
- nginx
- grammar
- stdlib
- oop
- dom
- bom
- htmlapi
- jquery
- tool
- advanced
- appendix
- library
- nodejs

introduction: 导论
nginx: Nginx
grammar: 基本语法
stdlib: 标准库
oop: 面向对象编程
dom: DOM
bom: 浏览器环境
htmlapi: HTML网页的API
jquery: jQuery
library: 草稿一：函数库
nodejs: 草稿二：Node.js
tool: 开发工具
advanced: 高级语法
appendix: 附录
