markdown: kramdown
highlighter: rouge
permalink: none
sitename: Web 开发博客

chapters:
- introduction
- dom
- htmlapi
- javascriptapi
- mobileweb
- nginx

# - grammar
# - stdlib
# - oop
# - bom
# - jquery
# - tool
# - advanced
# - appendix
# - library
# - nodejs

introduction: 导论
dom: DOM
htmlapi: HTML网页的API
javascriptapi: JavaScript
mobileweb: 移动 Web 开发
nginx: Nginx


# grammar: 基本语法
# stdlib: 标准库
# oop: 面向对象编程
# bom: 浏览器环境
# jquery: jQuery
# library: 草稿一：函数库
# nodejs: 草稿二：Node.js
# tool: 开发工具
# advanced: 高级语法
# appendix: 附录
